const DEFAULT_NAME='صيدلية الشفاء',DEFAULT_PASSWORD='1234',DEFAULT_CATEGORIES=['مسكنات','مضادات حيوية','فيتامينات','أدوية مزمنة','مستلزمات طبية'];
const getPassword=()=>localStorage.getItem('pharmacyPassword')||DEFAULT_PASSWORD;
const getName=()=>localStorage.getItem('pharmacyName')||DEFAULT_NAME;
const getImage=()=>localStorage.getItem('pharmacyImage')||'../assets/pharmacy.jpg';
const getCategories=()=>JSON.parse(localStorage.getItem('pharmacyCategories')||JSON.stringify(DEFAULT_CATEGORIES));
function showMessage(m,t='success'){const e=document.querySelector('[data-message]');if(!e)return;e.textContent=m;e.className='alert-system show '+(t==='error'?'alert-danger':'');setTimeout(()=>e.classList.remove('show'),3200)}
function applyBranding(){document.querySelectorAll('[data-pharmacy-name]').forEach(e=>e.textContent=getName());document.querySelectorAll('[data-pharmacy-image]').forEach(e=>e.src=getImage())}
function checkAuth(){if(sessionStorage.getItem('pharmacyLoggedIn')!=='true')location.href='../index.html'}
function login(){const i=document.getElementById('password'),m=document.getElementById('loginMessage');if(!i.value){m.textContent='الرجاء إدخال كلمة المرور';m.classList.add('show');return}if(i.value!==getPassword()){m.textContent='كلمة المرور غير صحيحة';m.classList.add('show');return}sessionStorage.setItem('pharmacyLoggedIn','true');location.href='pages/dashboard.html'}
function logout(){sessionStorage.removeItem('pharmacyLoggedIn');location.href='../index.html'}
function esc(v){return String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#039;','"':'&quot;'}[c]))}
function populateCategories(){const s=document.getElementById('category');if(s)s.innerHTML='<option value="">اختر التصنيف</option>'+getCategories().map(x=>`<option>${esc(x)}</option>`).join('')}
function loadMedicines(){const a=JSON.parse(localStorage.getItem('medicines')||'[]'),q=(document.getElementById('medicineSearch')?.value||'').toLowerCase(),b=document.getElementById('medicineBody');if(!b)return;const r=a.filter(x=>!q||x.name.toLowerCase().includes(q)||x.category.toLowerCase().includes(q));b.innerHTML=r.length?r.map((x,i)=>`<tr><td>${i+1}</td><td>${esc(x.name)}</td><td>${esc(x.category)}</td><td>${esc(x.quantity)}</td><td>${esc(x.purchasePrice)}</td><td>${esc(x.salePrice)}</td><td>${esc(x.expiry)}</td><td>${esc(x.supplier)}</td><td class="no-print"><button class="btn btn-sm btn-system" onclick="editMedicine(${x.id})">تعديل</button><button class="btn btn-sm btn-system btn-danger-soft" onclick="deleteMedicine(${x.id})">حذف</button></td></tr>`).join(''):'<tr><td colspan="9" class="text-center py-4">لا توجد أدوية مسجلة</td></tr>'}
function saveMedicine(e){e.preventDefault();const f=document.getElementById('medicineForm');if(!f.checkValidity()){f.classList.add('was-validated');showMessage('الرجاء استكمال الحقول المطلوبة','error');return}const d=Object.fromEntries(new FormData(f).entries()),id=Number(document.getElementById('medicineId').value||0),a=JSON.parse(localStorage.getItem('medicines')||'[]');if(id){const i=a.findIndex(x=>x.id===id);if(i>=0)a[i]={id,...d};showMessage('تم تحديث الدواء')}else{a.push({id:Date.now(),...d});showMessage('تم حفظ الدواء')}localStorage.setItem('medicines',JSON.stringify(a));f.reset();document.getElementById('medicineId').value='';document.getElementById('medicineSaveBtn').textContent='حفظ';loadMedicines()}
function editMedicine(id){const x=JSON.parse(localStorage.getItem('medicines')||'[]').find(x=>x.id===id);if(!x)return;Object.keys(x).forEach(k=>{const e=document.querySelector(`[name="${k}"]`);if(e)e.value=x[k]});document.getElementById('medicineId').value=id;document.getElementById('medicineSaveBtn').textContent='تحديث';scrollTo({top:0,behavior:'smooth'})}
function deleteMedicine(id){if(!confirm('هل أنت متأكد من حذف هذا الدواء؟'))return;localStorage.setItem('medicines',JSON.stringify(JSON.parse(localStorage.getItem('medicines')||'[]').filter(x=>x.id!==id)));loadMedicines();showMessage('تم حذف الدواء')}
function printMedicines(){window.print()}
function loadCategories(){const e=document.getElementById('categoryList');if(!e)return;e.innerHTML=getCategories().map((x,i)=>`<div class="class-row"><span>${esc(x)}</span><div class="class-actions"><button class="btn btn-sm btn-system" onclick="editCategory(${i})">تعديل</button><button class="btn btn-sm btn-system btn-danger-soft" onclick="deleteCategory(${i})">حذف</button></div></div>`).join('')}
function saveCategory(e){e.preventDefault();const n=document.getElementById('newCategory').value.trim();if(!n)return showMessage('اكتب اسم التصنيف أولاً','error');const i=Number(document.getElementById('categoryIndex').value),a=getCategories();if(i>=0){a[i]=n;showMessage('تم تعديل التصنيف')}else{a.push(n);showMessage('تمت إضافة التصنيف')}localStorage.setItem('pharmacyCategories',JSON.stringify(a));document.getElementById('categoryForm').reset();document.getElementById('categoryIndex').value='-1';document.getElementById('categorySaveBtn').textContent='إضافة تصنيف';loadCategories();populateCategories()}
function editCategory(i){document.getElementById('newCategory').value=getCategories()[i];document.getElementById('categoryIndex').value=i;document.getElementById('categorySaveBtn').textContent='تحديث التصنيف'}
function deleteCategory(i){if(!confirm('هل أنت متأكد من حذف هذا التصنيف؟'))return;const a=getCategories();a.splice(i,1);localStorage.setItem('pharmacyCategories',JSON.stringify(a));loadCategories();populateCategories();showMessage('تم حذف التصنيف')}
function loadSettings(){const n=document.getElementById('pharmacyNameInput');if(n)n.value=getName();const i=document.getElementById('settingsImage');if(i)i.src=getImage()}
function saveSettings(e){e.preventDefault();const n=document.getElementById('pharmacyNameInput').value.trim();if(!n)return showMessage('اكتب اسم الصيدلية','error');localStorage.setItem('pharmacyName',n);showMessage('تم حفظ الإعدادات');applyBranding()}
function loadPharmacyImage(e){const f=e.target.files[0];if(!f)return;const r=new FileReader();r.onload=x=>{localStorage.setItem('pharmacyImage',x.target.result);document.getElementById('settingsImage').src=x.target.result;showMessage('تم تغيير صورة الصيدلية')};r.readAsDataURL(f)}
function changePassword(e){e.preventDefault();const c=document.getElementById('currentPassword').value,n=document.getElementById('newPassword').value,cn=document.getElementById('confirmPassword').value;if(c!==getPassword())return showMessage('كلمة المرور الحالية غير صحيحة','error');if(n.length<4)return showMessage('كلمة المرور الجديدة يجب أن تكون 4 أحرف على الأقل','error');if(n!==cn)return showMessage('تأكيد كلمة المرور غير مطابق','error');localStorage.setItem('pharmacyPassword',n);document.getElementById('passwordForm').reset();showMessage('تم تغيير كلمة المرور بنجاح')}
document.addEventListener('DOMContentLoaded',()=>{applyBranding();if(document.body.dataset.protected==='true')checkAuth();populateCategories();loadMedicines();loadCategories();loadSettings();document.getElementById('loginForm')?.addEventListener('submit',e=>{e.preventDefault();login()});document.getElementById('medicineForm')?.addEventListener('submit',saveMedicine);document.getElementById('medicineSearch')?.addEventListener('input',loadMedicines);document.getElementById('categoryForm')?.addEventListener('submit',saveCategory);document.getElementById('settingsForm')?.addEventListener('submit',saveSettings);document.getElementById('pharmacyImageInput')?.addEventListener('change',loadPharmacyImage);document.getElementById('passwordForm')?.addEventListener('submit',changePassword)})
